modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="the_shade_mod"
version="1.0.0"
displayName="the shadows encroaching"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="theca, MCreator"

[[dependencies.the_shade_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




